#deployment "likes" created
apiVersion: apps/v1
kind: Deployment
metadata:
  name: likes-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: likes
  template:
    metadata:
      labels:
        app: likes
    spec:
      containers:
        - name: likes
          image: rtpa25/likes
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              value: "mongodb://likes-mongo-srv:27017/likes"
            - name: NATS_URI
              value: "nats://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: "insta"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
#service "likes-srv" created that enables networking between pods
apiVersion: v1
kind: Service
metadata:
  name: likes-srv
spec:
  selector:
    app: likes
  type: ClusterIP
  ports:
    - name: likes
      protocol: TCP
      port: 3000
      targetPort: 3000
