name: deploy-likes

on:
  push:
    branches:
      - main
    paths:
      - "likes/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd likes && docker build -t rtpa25/likes .
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push rtpa25/likes
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save micro-insta
      - run: kubectl rollout restart deployments likes-depl
