name: tests-comments

on:
  pull_request:
    paths:
      - "comments/**"
      - ".github/workflows/test-comments.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd comments && npm install && npm run test:ci
